### ISSUE TITLE
disable php warnings of workarround ?

### ISSUE THREAD

**Issue by DragonHeart69** [loganmarchione/docker-php-startpage#5]
![2022-04-15 10_19_57-DragonHeart's Home DashBoard - Brave](https://user-images.githubusercontent.com/21025274/163545598-21fac797-808f-4e14-bb26-a3eaff8254ae.png)
when a server is offline I get the following error message. I suspect these will disappear if you can disable debugging/warnings in the apache server. Or possibly some other workarround ? 
![2022-04-15 10_25_26-192 168 129 202 - Brave](https://user-images.githubusercontent.com/21025274/163546104-efc336b2-abe1-49e9-b404-c2a6cb203579.png)
?

**Comment by loganmarchione** [comment]
Ya I noticed this as well. Going to look into this by adding a try/except or something to `get_headers`.
`$headers = get_headers($url);`
